Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('cmds/*.c') + Glob('cmds/*.cpp')
CPPPATH = [cwd, ]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
